name: hpack
version: 0.1.2
synopsis: An alternative format for Haskell packages
maintainer: Simon Hengel <sol@typeful.net>
license: MIT
github: sol/hpack

ghc-options: -Wall

dependencies:
  - aeson >= 0.8
  - base == 4.*
  - base-compat >= 0.8
  - deepseq
  - directory
  - filepath
  - text
  - unordered-containers
  - yaml

source-dirs: src

executables:
  hpack:
    main: Main.hs
    source-dirs: driver

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec == 2.*
      - mockery
      - interpolate
